import { InMemoryDbService } from 'angular-in-memory-web-api';

export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const heroes = [
      { id: 0, name: 'Sr. Amazing' },
      { id: 1, name: 'Sr. Incrível' },
      { id: 2, name: 'Flash' },
      { id: 3, name: 'Super Junior' },
      { id: 4, name: 'Master Boy' },
      { id: 5, name: 'Cobalto' },
      { id: 6, name: 'Ametista' },
      { id: 7, name: 'Flora' },
      { id: 8, name: 'Violeta' },
      { id: 9, name: 'Camerói' },
      { id: 10, name: 'Sr Tudo' },
      { id: 11, name: 'Mr. Nice' },
      { id: 12, name: 'Narco' },
      { id: 13, name: 'Bombasto' },
      { id: 14, name: 'Celeritas' },
      { id: 15, name: 'Magneta' },
      { id: 16, name: 'RubberMan' },
      { id: 17, name: 'Dynama' },
      { id: 18, name: 'Dr IQ' },
      { id: 19, name: 'Magma' },
      { id: 20, name: 'Tornado' },
      { id: 21, name: 'Super Woman' },
      { id: 22, name: 'Narco' },
      { id: 23, name: 'Bolhasto' },
      { id: 24, name: 'Celeritas' },
      { id: 25, name: 'Super Homem' },
      { id: 26, name: 'RubberMan' },
      { id: 27, name: 'Dynama' },
      { id: 28, name: 'Dr IQ' },
      { id: 29, name: 'Magma' },
      { id: 30, name: 'Tornado' },
      { id: 31, name: 'Bat Girl' },
      { id: 32, name: 'Narco' },
      { id: 33, name: 'Bolhas' },
      { id: 34, name: 'Celeritas' },
      { id: 35, name: 'Magneto' },
      { id: 36, name: 'Pocahontas' },
      { id: 37, name: 'Dynama' },
      { id: 38, name: 'Dr Genio' },
      { id: 39, name: 'Cebruteos' },
      { id: 40, name: 'Tempestade' },
      { id: 41, name: 'Sr. Porta' },
      { id: 42, name: 'Sr. Incrível' },
      { id: 43, name: 'Flash' },
      { id: 44, name: 'Super Junior' },
      { id: 45, name: 'Master Yi' },
      { id: 46, name: 'Cobalto' },
      { id: 47, name: 'Ametista' },
      { id: 48, name: 'Flora' },
      { id: 49, name: 'Violeta' },
      { id: 50, name: 'Camerói' },
      { id: 51, name: 'Sr Tudo' },
      { id: 52, name: 'Mulher Gato' },
      { id: 53, name: 'Narco' },
      { id: 54, name: 'Boneco Do Bem' },
      { id: 55, name: 'Celeritas' },
      { id: 56, name: 'Batman' },
      { id: 57, name: 'RubberMan' },
      { id: 58, name: 'Dynama' },
      { id: 59, name: 'Dr IQ' },
      { id: 60, name: 'Magma' },
      { id: 61, name: 'Tornado' },
      { id: 62, name: 'Viúva Negra' },
      { id: 63, name: 'Narco' },
      { id: 64, name: 'Bebe Salva Mundo' },
      { id: 65, name: 'Celeritas' },
      { id: 66, name: 'Marvel' },
      { id: 67, name: 'RubberMan' },
      { id: 68, name: 'Dynama' },
      { id: 69, name: 'Dr IQ' },
      { id: 70, name: 'Magma' },
      { id: 71, name: 'Tornado' },
      { id: 72, name: 'Mulher Maravilha' },
      { id: 73, name: 'Narco' },
      { id: 74, name: 'Best Hero' },
      { id: 75, name: 'Celeritas' },
      { id: 76, name: 'Magneto' },
      { id: 77, name: 'Pocahontas' },
      { id: 78, name: 'Dynama' },
      { id: 79, name: 'Dr Genio' },
      { id: 80, name: 'Cebruteos' },
      { id: 81, name: 'Tempestade' },
      { id: 82, name: 'PoderoJo'}
    ];
    return {heroes};
  }
}
